[package]
name = "kani"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kani-verifier = "0.48.0"
proptest = "1.4.0"
